#! /usr/bin/env sh

function check_config() {
  if [ ! -f .playlister ];then
    echo ".playlister not found. Add it with the first line being the URL to the playlist." >&2
    exit 1
  elif [ ! -s .playlister ];then
    echo ".playlister is empty. The first line must be the URL to the playlist." >&2
    exit 2
  fi
}

function get_playlist_url() {
  PLAYLIST_URL=$(head -n1 .playlister)
}

function define_naming_format() {
  NAMING_FORMAT="%(playlist_index)s %(title)s.%(ext)s"
}

function set_default_values() {
  NUMBER_OF_FILES_TO_KEEP=10
}

function calculate_bounds() {
  PLAYLIST_START=$(echo $1|cut -d" " -f1|sed 's/^0*//')

  case $PLAYLIST_START in
    '' | *[!0-9]*)
      PLAYLIST_START=1;;
  esac

  PLALIST_END=$(($PLAYLIST_START + $NUMBER_OF_FILES_TO_KEEP - 1))
}

function download_active_part_of_playlist() {
  youtube-dl --playlist-start $PLAYLIST_START \
             --playlist-end $PLALIST_END \
             "$PLAYLIST_URL" \
             -o "$NAMING_FORMAT"
}

function delete_old_videos() {
  FILECOUNT=$(ls *.mp4|wc -l|tr -d " ")
  NUMBER_OF_FILES_TO_DELETE=$(($FILECOUNT - $NUMBER_OF_FILES_TO_KEEP))

  if [ $NUMBER_OF_FILES_TO_DELETE -gt 0 ];then
    ls *.mp4 | head -n $NUMBER_OF_FILES_TO_DELETE | perl -lne 'print quotemeta' | xargs rm
  fi
}

check_config
get_playlist_url
define_naming_format
set_default_values
calculate_bounds $1
download_active_part_of_playlist
delete_old_videos
